### ISSUE TITLE
Multiple input handling

### ISSUE THREAD

**Issue by emberborja** [whatnotery/fizzbuzz#4]
if a user puts in a new input without clearing the output, the new output is appended to the bottom of the old output and the newest clear button does not work. If this is output appending is the desired behavior that is fine, You could rework the event listener to grab all clear buttons and have them clear all output no matter which is pushed. You could alternatively have new input automatically clear the old output, you could have each clear button only clear the section of output it is tied to, etc...

**Comment by whatnotery** [comment]
kinda solved by disabling input until  clear is pressed

**Comment by whatnotery** [comment]
reworked this by wiping the output anytime new input is entered
