### ISSUE TITLE
Line characters rework

### ISSUE THREAD

**Issue by emberborja** [whatnotery/fizzbuzz#5]
At the moment each line is handled as a new div with a '>' character in the text node in front of the newest line of numerical input. You could rework this so that each number is a new list item in an unordered list and then change the li element from a disc to a '>'. You could also handle this by altering the ::before element in CSS. I think it is better practice to have the HTML formatted more intuitively by creating a list and then styling that list with CSS.

**Comment by whatnotery** [comment]
done!
